---
apiVersion: config.openshift.io/v1
items:
- apiVersion: config.openshift.io/v1
  kind: Authentication
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2025-08-27T14:42:15Z"
    generation: 2
    managedFields:
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:include.release.openshift.io/ibm-cloud-managed: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:release.openshift.io/create-only: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"c92770dd-1499-41de-a1f6-505d0092b485"}: {}
        f:spec: {}
      manager: cluster-version-operator
      operation: Update
      time: "2025-08-27T14:42:15Z"
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:oauthMetadata:
            .: {}
            f:name: {}
          f:serviceAccountIssuer: {}
          f:type: {}
          f:webhookTokenAuthenticator:
            .: {}
            f:kubeConfig:
              .: {}
              f:name: {}
      manager: authentication-operator
      operation: Update
      time: "2025-08-27T14:46:43Z"
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:integratedOAuthMetadata:
            .: {}
            f:name: {}
      manager: authentication-operator
      operation: Update
      subresource: status
      time: "2025-08-27T14:54:52Z"
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: c92770dd-1499-41de-a1f6-505d0092b485
    resourceVersion: "20504"
    uid: 2ffc485a-4422-45eb-9b94-a53343ecc70b
  spec:
    oauthMetadata:
      name: ""
    serviceAccountIssuer: ""
    type: ""
    webhookTokenAuthenticator:
      kubeConfig:
        name: webhook-authentication-integrated-oauth
  status:
    integratedOAuthMetadata:
      name: oauth-openshift
kind: AuthenticationList
metadata:
  continue: ""
  resourceVersion: "124482"
