apiVersion: operator.openshift.io/v1
kind: Authentication
metadata:
  name: cluster
status:
  conditions:
  - lastTransitionTime: "2025-08-07T22:38:20Z"
    message: ""
    reason: AsExpected
    status: "False"
    type: OpenshiftAuthenticationStaticResourcesDegraded
