---
apiVersion: v1
items:
- apiVersion: v1
  data:
    v4-0-config-system-session: MjAzIGJ5dGVzIGxvbmc=
  kind: Secret
  metadata:
    creationTimestamp: "2025-08-01T18:44:36Z"
    labels:
      app: oauth-openshift
    managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:v4-0-config-system-session: {}
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:type: {}
        manager: authentication-operator
        operation: Update
        time: "2025-08-01T18:44:36Z"
    name: v4-0-config-system-session
    namespace: openshift-authentication
    resourceVersion: "20293"
    uid: 1ab2c769-1f5b-4442-8652-ed0ebbded1a7
  type: Opaque
- apiVersion: v1
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGRENDQXZ5Z0F3SUJBZ0lJZUIwRFlEaVV4Qm93RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMU5EQTNNekkxTlRBZQpGdzB5TlRBNE1ERXhPRE0wTXpkYUZ3MHlOekE0TURFeE9ETTBNemhhTURjeE5UQXpCZ05WQkFNVExHOWhkWFJvCkxXOXdaVzV6YUdsbWRDNXZjR1Z1YzJocFpuUXRZWFYwYUdWdWRHbGpZWFJwYjI0dWMzWmpNSUlCSWpBTkJna3EKaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE0T1dwQXowL015aGh2NC9OMytmeXcwNklES0FBZ3V3UgpnOTBoZ0NxMFpjWTJPdW12SXlxdDFoM0t2ZlFWdkdwMU54L0JCQkc2SzYwRE1WRUJqRnhNZlhLVTM1UTR5OURtCnRCVTF5eHJnVFR3bDNEajZ2cm9vTGx5dUFKRG1xQW9CbG1LeHFSS3NTVnEwa3FmTDRVT0UrZHljWUJJSUZhVWoKRnBIK203VHNSYUhBa2ljNzFoTDBSeklsMUNWVmZsTUppNUFkYitkY2c3TzQ2VFVYYmE3S0o0TThzeFhvUzA5cgpEZ1NtZWpCUHBhc1pIVnM2UloyOVFBeUpSeDQ2Q0pMWWNncHlkakp2cjZoSnljM09GZXQ3ZUNzVVRvZjUyeGlSCmt0aUhidGF1cWVKTklQY2J3czg0UytOb3h0aEY1TXp4QlJFTGc4Y1F5eEF3eXp3RkVsYkR1UUlEQVFBQm80SUIKSXpDQ0FSOHdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUJNQXdHQTFVZApFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGTWJSVzRURUpvejMyYkdDQlFlZDlZNTZQZTJwTUI4R0ExVWRJd1FZCk1CYUFGTjgzR253MEZCcHRqakdSblpDNW1CRmpiVFpXTUhNR0ExVWRFUVJzTUdxQ0xHOWhkWFJvTFc5d1pXNXoKYUdsbWRDNXZjR1Z1YzJocFpuUXRZWFYwYUdWdWRHbGpZWFJwYjI0dWMzWmpnanB2WVhWMGFDMXZjR1Z1YzJocApablF1YjNCbGJuTm9hV1owTFdGMWRHaGxiblJwWTJGMGFXOXVMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNRFVHCkN5c0dBUVFCa2dnUlpBSUJCQ1lUSkRjMU1XWmtOVEF3TFRWak4yRXROR0kxT1MwNFl6WTBMV1ZoT0dGaFpEVTQKTnprMU5EQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFHclpQMGR2L1Y0QlVVSkErU2NrVTBFNittQ0tiQ01oTwpvY2IvYTV6S3hkQkVsL0pSWUg0UFNmRFpPUmppNDVTQTBBZisvaXlZVWdaaXdBb3V6VjZYOC9NMFZUNTIwNUlMCmczcExaSjY3aGhQUytNdG1nU0xROW9JV0gwcHMrQVFpc2krTzFVeHVTMFVaNGwwU3dObFJDYk5Lclc2NTdLU0EKTWI3S1BNaG90VXRRcjdiZXZKS3k3MHFsNzhDZmMrSjcvdngySlhsbThZSE9mMUxCNERGMnBSRW02THJpVGhLMQpkazZQaWNicHZLYXZuRWJJeDhlQ3lyTDdBNFg0ZHFpTXBYalU5VE5qZFVjWUN3eGtncEJ3dys3Yk5DSDhLTlFaCk9oWkF2NzNMUGI5R0JyS1RadGxma2dkM01tUWNBMWVHRW4zb0RIWjd0US9lUFdjOXYzMG8wdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lJUElnQk9nNnlLSFl3RFFZSktvWklodmNOQVFFTEJRQXdOakUwTURJR0ExVUUKQXd3cmIzQmxibk5vYVdaMExYTmxjblpwWTJVdGMyVnlkbWx1WnkxemFXZHVaWEpBTVRjMU5EQTNNekkxTlRBZQpGdzB5TlRBNE1ERXhPRE0wTVRWYUZ3MHlOekE1TXpBeE9ETTBNVFphTURZeE5EQXlCZ05WQkFNTUsyOXdaVzV6CmFHbG1kQzF6WlhKMmFXTmxMWE5sY25acGJtY3RjMmxuYm1WeVFERTNOVFF3TnpNeU5UVXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRGhCTHM4aHN0ckgxYkVWOFZUK1Z3L2hKT1RUay9SUmhOZQprM2ptMUR5elFJenZIZllVS1lpZzBJeThHTUZ6a0c1SDdDQUllK2VaN1pWcmZWUTlPV2FIUWJHK0xsTDZkaDFNCnlnc1l6RlhDbTZ3c0tndHlVMG9XblBVYUk0VE15RWI0bVhXVU95TGZtSWJiWVA2RU9EQXdsbUVkZG1wdnVQVkYKNXVFek1LSGVtRDY3enE4Z3Fsc0JGSytLOXV3bmpNWHhWdHBzRUhpK3locEUwbVNxRW1mbHl2b1VMc1l1KzFjRQpTZi94Y2E4NUEvNTJtNTBYTWl1TWZJV1VYbk81djA2c2NmM3pwZkdWWm9FVk5TaWxNOUdJdTIvbXhWWm9DUHM1CkdRY3dJTTFwdENBVGtEVGo3MGNuNWp4Z1hQMloyT093SldDakNtQUVmM1JLejJrWXY5N0RBZ01CQUFHall6QmgKTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlRmTnhwOApOQlFhYlk0eGtaMlF1WmdSWTIwMlZqQWZCZ05WSFNNRUdEQVdnQlRmTnhwOE5CUWFiWTR4a1oyUXVaZ1JZMjAyClZqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFvUitGMWlTMnBySk5yT2ZtRm91TXdlQjlLUVU0dWpqWEV4TUYKakF4NEorZVl4SVdIY3ozRnNGYy9YOTZZRm9zQ1JUVjFya0x5TEJ6MXlzbTNHeUFJYnVoSzBzWDFzbEtxUDYrMgpzdDBmeWNuZkxQdXVoa3dxU05SQUd5eEdjVTA1cjhlak9WMnlTcTRQUW5aR0pFc1g1Q25wS3BKZ3UybUhGSnpBCnJHREs2UzdXaFI1Vml4RjYxeFE0OXdUem96VzY2UHVxd2lrSGcrTDliY1VQcitIR3RveDRya1BGdWQ1a0tpZXoKSFhLZWVtc1M3Y1pqTlFwZkp3MW1qcDZPSnBJblEyaEc3TDV5eXd1NDAvMTNGbjlTV2JUdWNCVThzZXZLdWtEeQp3TFd2Um85Nlg5TkFIL0c2WG5aS2FVRU1wTFhyYXBJeW8rNFB5cTl5U0pGMzNaTTgxUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: MTY3OSBieXRlcyBsb25n
  kind: Secret
  metadata:
    annotations:
      openshift.io/description: 'Secret contains a pair signed serving certificate/key
        that is generated by Service CA operator for service/oauth-openshift with
        hostname oauth-openshift.openshift-authentication.svc and is annotated to
        the service with annotating a service resource with ''service.beta.openshift.io/serving-cert-secret-name:
        v4-0-config-system-serving-cert''. The certificate is valid for 2 years.'
      openshift.io/owning-component: service-ca
      service.alpha.openshift.io/expiry: "2027-08-01T18:34:38Z"
      service.alpha.openshift.io/originating-service-name: oauth-openshift
      service.alpha.openshift.io/originating-service-uid: 751fd500-5c7a-4b59-8c64-ea8aad587954
      service.beta.openshift.io/expiry: "2027-08-01T18:34:38Z"
    creationTimestamp: "2025-08-01T18:34:39Z"
    managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:tls.crt: {}
            f:tls.key: {}
          f:metadata:
            f:annotations:
              .: {}
              f:openshift.io/description: {}
              f:openshift.io/owning-component: {}
              f:service.alpha.openshift.io/expiry: {}
              f:service.alpha.openshift.io/originating-service-name: {}
              f:service.alpha.openshift.io/originating-service-uid: {}
              f:service.beta.openshift.io/expiry: {}
            f:ownerReferences:
              .: {}
              k:{"uid":"751fd500-5c7a-4b59-8c64-ea8aad587954"}: {}
          f:type: {}
        manager: service-ca-operator
        operation: Update
        time: "2025-08-01T18:34:39Z"
    name: v4-0-config-system-serving-cert
    namespace: openshift-authentication
    ownerReferences:
      - apiVersion: v1
        kind: Service
        name: oauth-openshift
        uid: 751fd500-5c7a-4b59-8c64-ea8aad587954
    resourceVersion: "8578"
    uid: ad75ddb5-40ed-4a32-bc8d-41c0fd4a0dad
  type: kubernetes.io/tls
- apiVersion: v1
  data:
    apps.ci-op-gn2pz6q7-69aee.XXXXXXXXXXXXXXXXXXXXXX: NDEwNCBieXRlcyBsb25n
  kind: Secret
  metadata:
    creationTimestamp: "2025-08-01T18:34:45Z"
    managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:apps.ci-op-gn2pz6q7-69aee.XXXXXXXXXXXXXXXXXXXXXX: {}
          f:type: {}
        manager: authentication-operator
        operation: Update
        time: "2025-08-01T18:34:45Z"
    name: v4-0-config-system-router-certs
    namespace: openshift-authentication
    resourceVersion: "8802"
    uid: da379869-e11c-4267-a98d-26a516b0c511
  type: Opaque
- apiVersion: v1
  data:
    errors.html: MTM4ODYyIGJ5dGVzIGxvbmc=
    login.html: MTcyOTExIGJ5dGVzIGxvbmc=
    providers.html: MTQ3NjYwIGJ5dGVzIGxvbmc=
  kind: Secret
  metadata:
    creationTimestamp: "2025-08-01T18:34:24Z"
    managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:errors.html: {}
            f:login.html: {}
            f:providers.html: {}
          f:type: {}
        manager: authentication-operator
        operation: Update
        time: "2025-08-01T18:34:24Z"
    name: v4-0-config-system-ocp-branding-template
    namespace: openshift-authentication
    resourceVersion: "6993"
    uid: ae89f1f0-cafc-4bee-8605-13145129825d
  type: Opaque
kind: SecretList
metadata:
  resourceVersion: "269056"
