apiVersion: operator.openshift.io/v1
kind: Authentication
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  name: cluster
spec:
  managementState: Managed
  observedConfig:
    oauthAPIServer:
      apiServerArguments:
        api-audiences:
        - https://kubernetes.default.svc
        cors-allowed-origins:
        - //127\.0\.0\.1(:|$)
        - //localhost(:|$)
        feature-gates: []
        tls-cipher-suites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        tls-min-version: VersionTLS12
    oauthServer:
      serverArguments: null
  unsupportedConfigOverrides: null
