---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-09-09T00:02:45Z"
  generation: 9
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:release.openshift.io/create-only: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"4e11cec4-056d-4b95-a391-a0912318fa40"}: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2025-09-09T00:02:45Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:templates:
          .: {}
          f:error:
            .: {}
            f:name: {}
          f:login:
            .: {}
            f:name: {}
          f:providerSelection:
            .: {}
            f:name: {}
        f:tokenConfig: {}
    manager: e2e.test
    operation: Update
    time: "2025-09-09T01:04:34Z"
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 4e11cec4-056d-4b95-a391-a0912318fa40
  resourceVersion: "51279"
  uid: 6002deab-6df1-4107-979e-e9986bb93fd9
spec:
  templates:
    error:
      name: ""
    login:
      name: ""
    providerSelection:
      name: ""
  tokenConfig: {}
