---
apiVersion: config.openshift.io/v1
items:
- apiVersion: config.openshift.io/v1
  kind: OAuth
  metadata:
    annotations:
      include.release.openshift.io/ibm-cloud-managed: "true"
      include.release.openshift.io/self-managed-high-availability: "true"
      release.openshift.io/create-only: "true"
    creationTimestamp: "2025-08-01T18:29:57Z"
    generation: 1
    managedFields:
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:include.release.openshift.io/ibm-cloud-managed: {}
            f:include.release.openshift.io/self-managed-high-availability: {}
            f:release.openshift.io/create-only: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"fd412cff-9592-4cb6-b0e9-97a5c376f29e"}: {}
        f:spec: {}
      manager: cluster-version-operator
      operation: Update
      time: "2025-08-01T18:29:57Z"
    name: cluster
    ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: fd412cff-9592-4cb6-b0e9-97a5c376f29e
    resourceVersion: "1775"
    uid: ffaa4e11-4ed6-49c4-b520-c9d79c19d6ff
  spec: {}
kind: OAuthList
metadata:
  continue: ""
  resourceVersion: "269027"
