apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: oauth-apiserver-pdb
  namespace: openshift-oauth-apiserver
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      apiserver: "true"
      app: openshift-oauth-apiserver
  unhealthyPodEvictionPolicy: AlwaysAllow
status:
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 0
