apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-authentication-operator
  name: origin-cluster-authentication-operator-config
data:
  operator-config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
