apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:operator:osin
roleRef:
  kind: ClusterRole
  name: cluster-admin  # TODO fix, this is madness
subjects:
- kind: ServiceAccount
  namespace: openshift-core-operators
  name: origin-cluster-osin-operator
