apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-core-operators
  name: origin-cluster-osin-operator-config
data:
  operator-config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
