apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-core-operators
  name: origin-cluster-osin-operator
  labels:
    app: origin-cluster-osin-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: origin-cluster-osin-operator
  template:
    metadata:
      name: origin-cluster-osin-operator
      labels:
        app: origin-cluster-osin-operator
    spec:
      serviceAccountName: origin-cluster-authentication-operator
      containers:
      - name: operator
        image: quay.io/openshift/origin-cluster-authentication-operator:latest
        imagePullPolicy: IfNotPresent
        command: ["authentication-operator", "operator"]
        args:
        - "--config=/var/run/configmaps/config/operator-config.yaml"
        - "-v=4"
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
      volumes:
      - name: config
        configMap:
          defaultMode: 440
          name: origin-cluster-authentication-operator-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - operator: Exists
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-authentication-operator
  name: origin-cluster-authentication-operator
  labels:
    app: origin-cluster-authentication-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: origin-cluster-authentication-operator
  template:
    metadata:
      name: origin-cluster-authentication-operator
      labels:
        app: origin-cluster-authentication-operator
    spec:
      serviceAccountName: origin-cluster-authentication-operator
      containers:
      - name: operator
        image: quay.io/openshift/origin-cluster-authentication-operator:latest
        imagePullPolicy: IfNotPresent
        command: ["authentication-operator", "operator"]
        args:
        - "--config=/var/run/configmaps/config/operator-config.yaml"
        - "-v=4"
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        env:
        - name: IMAGE
          value: quay.io/openshift/origin-hypershift:v4.0
        - name: OPERATOR_IMAGE
          value: docker.io/openshift/origin-cluster-authentication-operator:v4.0  # I believe this is supposed to exist
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        terminationMessagePolicy: FallbackToLogsOnError
      volumes:
      - name: config
        configMap:
          defaultMode: 440
          name: origin-cluster-authentication-operator-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - operator: Exists
