apiVersion: v1
kind: Namespace
metadata:
  name: openshift-authentication-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    openshift.io/node-selector: ""
    include.release.openshift.io/single-node-production-edge: "true"
  labels:
    openshift.io/cluster-monitoring: "true"
