kind: ConfigMap
apiVersion: v1
metadata:
  name: service-ca-bundle
  namespace: openshift-authentication-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    service.beta.openshift.io/inject-cabundle: "true"
    include.release.openshift.io/single-node-production-edge: "true"
data: {}
