---
apiVersion: config.openshift.io/v1
kind: Console
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-09-09T00:02:40Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:release.openshift.io/create-only: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"4e11cec4-056d-4b95-a391-a0912318fa40"}: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2025-09-09T00:02:40Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:consoleURL: {}
    manager: console
    operation: Update
    subresource: status
    time: "2025-09-09T00:28:55Z"
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 4e11cec4-056d-4b95-a391-a0912318fa40
  resourceVersion: "28767"
  uid: 2f7d522e-bcdf-495b-a1ed-7654a67428a0
spec: {}
status:
  consoleURL: https://console-openshift-console.apps.ci-op-j2wdcvij-465b4.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
