apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-10-14T22:38:20Z"
involvedObject:
  kind: Deployment
  name: authentication-operator
  namespace: openshift-authentication-operator
kind: Event
lastTimestamp: "2024-10-14T22:38:20Z"
message: Created ConfigMap/audit -n openshift-authentication because it was missing
metadata:
  name: authentication-operator.17fe72c59b829800.ce8a3f4a
  namespace: openshift-authentication-operator
reason: ConfigMapCreated
reportingComponent: ""
reportingInstance: ""
source:
  component: cluster-authentication-operator-run-once-sync-context
type: Normal
