---
apiVersion: config.openshift.io/v1
kind: Authentication
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-09-09T00:02:35Z"
  generation: 2
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:include.release.openshift.io/ibm-cloud-managed: {}
          f:include.release.openshift.io/self-managed-high-availability: {}
          f:release.openshift.io/create-only: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"4e11cec4-056d-4b95-a391-a0912318fa40"}: {}
      f:spec: {}
    manager: cluster-version-operator
    operation: Update
    time: "2025-09-09T00:02:35Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:oauthMetadata:
          .: {}
          f:name: {}
        f:serviceAccountIssuer: {}
        f:type: {}
        f:webhookTokenAuthenticator:
          .: {}
          f:kubeConfig:
            .: {}
            f:name: {}
    manager: authentication-operator
    operation: Update
    time: "2025-09-09T00:09:38Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:integratedOAuthMetadata:
          .: {}
          f:name: {}
    manager: authentication-operator
    operation: Update
    subresource: status
    time: "2025-09-09T00:28:53Z"
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 4e11cec4-056d-4b95-a391-a0912318fa40
  resourceVersion: "28653"
  uid: 754dd8b4-162a-4a2e-bb16-45b45eef47c1
spec:
  oauthMetadata:
    name: ""
  serviceAccountIssuer: ""
  type: ""
  webhookTokenAuthenticator:
    kubeConfig:
      name: webhook-authentication-integrated-oauth
status:
  integratedOAuthMetadata:
    name: oauth-openshift
