apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    synthetic.mom.openshift.io/controller-instance-name: TODO-staticResourceController
  creationTimestamp: null
  name: system:openshift:oauth-servercert-trust
  namespace: openshift-config-managed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:openshift:oauth-servercert-trust
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
