apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: system:openshift:oauth-servercert-trust
  namespace: openshift-config-managed
rules:
- apiGroups:
  - ""
  resourceNames:
  - oauth-serving-cert
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
