apiVersion: v1
kind: Service
metadata:
  annotations:
    operator.openshift.io/spec-hash: d9e6d53076d47ab2d123d8b1ba8ec6543488d973dcc4e02349493cd1c33bce83
    service.alpha.openshift.io/serving-cert-secret-name: v4-0-config-system-serving-cert
  labels:
    app: oauth-openshift
  name: oauth-openshift
  namespace: openshift-authentication
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  selector:
    app: oauth-openshift
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
