apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  generateName: system:openshift:openshift-authenticator-
  labels:
    authentication.openshift.io/csr: openshift-authenticator
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQkRUQ0J0QUlCQURCU01WQXdUZ1lEVlFRREUwZHplWE4wWlcwNmMyVnlkbWxqWldGalkyOTFiblE2YjNCbApibk5vYVdaMExXOWhkWFJvTFdGd2FYTmxjblpsY2pwdmNHVnVjMmhwWm5RdFlYVjBhR1Z1ZEdsallYUnZjakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQktUTC9xSUdtM05BZURxVmQzSVREQ1RnSFAwb2lYVkwKUU1HVTR0Q09Bckg5am8rYjBNUmJ3bkpTN0p3dmVYMlVXY0c2ajBXcVpsTGZUaTRyOG83cUNtMmdBREFLQmdncQpoa2pPUFFRREFnTklBREJGQWlBdExDYm1PVXR3RmRqVlJCWjZGbFhkNVFFV1Z4dFZWV1RQRXhRL2sxWGVxUUloCkFMcjBDTEZzYzFlVmJraHRUMEZsQ1k5UmliNWxkZ2ROalBZV0VwZ1hlTjJTCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
status: {}
