apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  generateName: system:openshift:openshift-authenticator-
  labels:
    authentication.openshift.io/csr: openshift-authenticator
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQkRUQ0J0QUlCQURCU01WQXdUZ1lEVlFRREUwZHplWE4wWlcwNmMyVnlkbWxqWldGalkyOTFiblE2YjNCbApibk5vYVdaMExXOWhkWFJvTFdGd2FYTmxjblpsY2pwdmNHVnVjMmhwWm5RdFlYVjBhR1Z1ZEdsallYUnZjakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkJZQ2wyaXdqamgwS2xDb0JhbklLRVB4SXVaOEFuNFcKNm96TGNQdWhKWDkwSmgrQzVmLzVyWEtZRkZRdFFrMnZ2QlJYSUhyNlhJUVhYUlZWUXNOMnA4bWdBREFLQmdncQpoa2pPUFFRREFnTklBREJGQWlFQXFDZTBjOFVEQXRPdlVQSjhvRTZXcUFqdk9BUkIrakxOVG5GR3dDNFdnY1VDCklHeU15TGY2YVVTRUVERmUvQ2F5Vm5nQ2o2bDJ5a1JBLzJuckhZc0hpYUpsCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
status: {}
