apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  generateName: system:openshift:openshift-authenticator-
  labels:
    authentication.openshift.io/csr: openshift-authenticator
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQkRqQ0J0QUlCQURCU01WQXdUZ1lEVlFRREUwZHplWE4wWlcwNmMyVnlkbWxqWldGalkyOTFiblE2YjNCbApibk5vYVdaMExXOWhkWFJvTFdGd2FYTmxjblpsY2pwdmNHVnVjMmhwWm5RdFlYVjBhR1Z1ZEdsallYUnZjakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkh0a0lWek9qTnI4OEVSeUxUbGpYZ1lLeURIeCtGbWQKRUJKSldqZ3NoNFpmY3BjWUJKd2YwWmxlVFNBMjFEZnQvNzdSbDhmNWJ0QXJzV1ZNbFNGbjl1Q2dBREFLQmdncQpoa2pPUFFRREFnTkpBREJHQWlFQWgyenZud3I2VTBmSHluQXI4Q3RjWWFRN3FxQ3ZISDdVZXF3eGdKVHJwT2NDCklRQ2E4Z3RrS3A3cXBZdmdXOTZDYitMb05ZU0xYY2YvZXdodWR6b05uemlETXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
status: {}
