action: Create
controllerInstanceName: TODO-staticResourceController
generateName: ""
name: v4-0-config-system-ocp-branding-template
namespace: openshift-authentication
resourceType:
  Group: ""
  Resource: secrets
  Version: v1
