action: Create
controllerInstanceName: TODO-payloadConfigController
generateName: ""
mame: v4-0-config-system-session
namespace: openshift-authentication
resourceType:
  Group: ""
  Resource: secrets
  Version: v1
