apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:openshift:useroauthaccesstoken-manager
rules:
- apiGroups:
  - oauth.openshift.io
  resources:
  - useroauthaccesstokens
  verbs:
  - get
  - list
  - watch
  - delete
